// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlQbjKbsvIPm4LuQHFxF3aC8tUtQ8__6s',
    appId: '1:671639752722:web:120dda1fb26e2d5dc288cb',
    messagingSenderId: '671639752722',
    projectId: 'aagis-1d4a5',
    authDomain: 'aagis-1d4a5.firebaseapp.com',
    databaseURL: 'https://aagis-1d4a5-default-rtdb.firebaseio.com',
    storageBucket: 'aagis-1d4a5.firebasestorage.app',
    measurementId: 'G-T5MVZTYCTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIhTgKAplET3EMCkGnnB1RBPy0Dx0O4Q',
    appId: '1:93161577759:android:19a6cc667c4bbc8fd1e42a',
    messagingSenderId: '93161577759',
    projectId: 'tera-health-database',
    storageBucket: 'tera-health-database.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZ5zxd7BgWkQIT0DfsyS_tHtAXbdJkpk',
    appId: '1:671639752722:ios:5d26a72e2476d7edc288cb',
    messagingSenderId: '671639752722',
    projectId: 'aagis-1d4a5',
    databaseURL: 'https://aagis-1d4a5-default-rtdb.firebaseio.com',
    storageBucket: 'aagis-1d4a5.firebasestorage.app',
    iosBundleId: 'com.example.teraHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZ5zxd7BgWkQIT0DfsyS_tHtAXbdJkpk',
    appId: '1:671639752722:ios:5d26a72e2476d7edc288cb',
    messagingSenderId: '671639752722',
    projectId: 'aagis-1d4a5',
    databaseURL: 'https://aagis-1d4a5-default-rtdb.firebaseio.com',
    storageBucket: 'aagis-1d4a5.firebasestorage.app',
    iosBundleId: 'com.example.teraHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlQbjKbsvIPm4LuQHFxF3aC8tUtQ8__6s',
    appId: '1:671639752722:web:77b7eddfd9306f32c288cb',
    messagingSenderId: '671639752722',
    projectId: 'aagis-1d4a5',
    authDomain: 'aagis-1d4a5.firebaseapp.com',
    databaseURL: 'https://aagis-1d4a5-default-rtdb.firebaseio.com',
    storageBucket: 'aagis-1d4a5.firebasestorage.app',
    measurementId: 'G-K35RS0G6EC',
  );
}
